<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYp7C3vF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYp7C3vF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYp7C3vF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYp7C3vF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYp7C3vF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Yp7C3vF',
    'container.build_id' => '4b2473a4',
    'container.build_time' => 1584998069,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYp7C3vF');
