<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWBg34uE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWBg34uE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWBg34uE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWBg34uE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWBg34uE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WBg34uE',
    'container.build_id' => '3f69af5b',
    'container.build_time' => 1585171802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWBg34uE');
